-
  name:  Networkteam.Neos.Shariff
  uriPattern: shariff
  defaults:
    '@package': Networkteam.Neos.Shariff
    '@controller': Shariff
    '@action': counts
    '@format': json
  appendExceedingArguments: true
