Neos:
  Flow:
    mvc:
      routes:
        'Networkteam.Neos.Shariff':
          position: 'before Neos.Neos'
    reflection:
      ignoredTags:
        unstable: true
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Shariff: true

Networkteam:
  Neos:
    Shariff:
      frontend:
        theme: standard
        buttonStyle: standard
        orientation: horizontal
        language: en
      options:
        domain: null
        cache:
          ttl: 3600
        services:
#          - AddThis
#          - Diaspora
#          - Facebook
#          - Flattr
#          - GooglePlus
#          - Info
#          - LinkedIn
#          - Mail
#          - Pinterest
#          - Qzone
#          - Reddit
#          - StumbleUpon
#          - tencent-weibo
#          - Threema
#          - tumblr
#          - Twitter
#          - weibo
#          - Whatsapp
#          - Xing
