TYPO3:
  Flow:
    object:
      excludeClasses:
        'zendframework.zendcache': ['.*']
        'zendframework.zendconfig': ['.*']
        'zendframework.zendcode': ['.*']
        'react.promise': ['.*']
        'zendframework.zendmath': ['.*']
    reflection:
      ignoredTags:
        unstable: 'unstable'

  Neos:
    typoScript:
      autoInclude:
        'Networkteam.Neos.Shariff': TRUE

Networkteam:
  Neos:
    Shariff:
      frontend:
        theme: standard
        orientation: horizontal
        language: en
      options:
        domain: 'your-domain.tld'
        cache:
          ttl: 1
        services:
#          - Facebook
#          - GooglePlus
#          - Twitter
#          - LinkedIn
#          - Reddit
#          - StumbleUpon
#          - Flattr
#          - Pinterest
#          - Xing
